### PR TITLE
chore: build the typography styleguide

### PR DESCRIPTION
**Pull request by alabobriggs**
#### What does this PR do
Build a typography styleguide and typography.md file to document all classes used

#### Description of Task to be completed
A typography demo page is created in the demo folder that shows how to use different fonts on the site and also different font size. The typography.md file shows how this classes are to be applied

#### How should this be manually tested
after running `npm run develop` locally visit the [development server link](http://localhost:8000/demo/typography-demo-page) and you can see the page. The typography.md file is in the root directory

#### What are the relevant issues this PR belongs to
#3 

#### Any background context you want to add
the tailwind-demo-page was also refactored to fit in how the demo pages whould appear as the previously used layout added some elements that wasn't necessary for the page

#### Screenshots

Screenshot from 2019-12-20 03-48-48

### CODE REVIEW

**Comment by alabobriggs** [comment]
> Great work chief. 
> 
> Although fonts have been added already in #59 as there was some delay with this task. You can pull master and check if you want to make any changes here before we merge.
> 
> Also, we might not need some variations of the fonts for this project.

Okay. I will remove the variations

**Comment by BolajiAyodeji** [comment]
Hello @alabobriggs , any updates here?

**Comment by alabobriggs** [comment]
Yes @BolajiAyodeji I will push online

**Comment by alabobriggs** [comment]
I don't want to continually delay the issue. I am really sorry for the delay

**Comment by BolajiAyodeji** [comment]
It's fine @alabobriggs, thanks for being open.

**Pull request closed without merging**
